image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/

# TODO Bootstrap some demo media/tags.
tasks:
  - init: >
      cp -a ~/beevenue-ui . &&
      beevenue_backend=$(gp url 7000) && sed -e "s,%%GITPOD_BACKEND_URL%%,$beevenue_backend," -i ui-config.json &&
      mv ui-config.json beevenue-ui/src/config.json
    command: cd beevenue-ui && npm start
  - init: >
      cp -a ~/beevenue . &&
      beevenue_frontend=$(gp url 3000) && sed -e "s,%%GITPOD_FRONTEND_URL%%,$beevenue_frontend," -i beevenue_config.py &&
      mv beevenue_config.py beevenue/ &&
      mv beevenue_rules.json beevenue/ &&
      cd beevenue &&
      env BEEVENUE_SKIP_SPINDEX=1 BEEVENUE_CONFIG_FILE="$(realpath beevenue_config.py)" FLASK_APP="$(realpath main.py)" flask db upgrade &&
      python insert_demo_data.py &&
      cd ..
    command: cd beevenue && bash main.sh
