image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/

# TODO: Create some config files and move them into the respective folders before starting the dev servers.
tasks:
  - init: >
      cp -a ~/beevenue-ui . && cd beevenue-ui && npm install && cd .. &&
      mv ui-config.json beevenue-ui/src/config.json
    command: cd beevenue-ui && npm start
  - init: >
      cp -a ~/beevenue . && cd beevenue && pip install -r requirements.txt &&
      pip install -r requirements.linuxonly.txt
    command: bash main.sh
