image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - init: >
      cp -a ~/beevenue-ui . &&
      mv ui-config.json beevenue-ui/src/config.json
    command: cd beevenue-ui && npm start
  - init: >
      cp -a ~/beevenue . &&
      mv beevenue_config.py beevenue/ &&
      mv beevenue_rules.json beevenue/ &&
      env BEEVENUE_SKIP_SPINDEX=1 BEEVENUE_CONFIG_FILE="$(realpath beevenue_config.py)" FLASK_APP="$(realpath main.py)" flask db upgrade
    command: cd beevenue && bash main.sh
