image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/

# TODO: Create some config files and move them into the respective folders before starting the dev servers.
tasks:
  - init: >
      cp -a ~/beevenue-ui .
    command: cd beevenue-ui && npm start
  - init: >
      cp -a ~/beevenue .
    command: bash main.sh
