DEBUG = True

SQLALCHEMY_DATABASE_URI = "sqlite:///gitpod.sqlite"
SQLALCHEMY_TRACK_MODIFICATIONS = False

SEND_FILE_MAX_AGE_DEFAULT = 604800

BEEVENUE_ALLOWED_CORS_ORIGINS = [
    "http://localhost:3000",
    "%%GITPOD_FRONTEND_URL%%",
]

BEEVENUE_THUMBNAIL_SIZES = {"s": 240, "l": 600}

BEEVENUE_TINY_THUMBNAIL_SIZE = 32
BEEVENUE_MINIMUM_ASPECT_RATIO = 0.5

BEEVENUE_RULES_FILE = "./beevenue_rules.json"

CACHE_DIR = "./beevenue_cache"

COMMIT_ID = "asdf"

SASHIMMIE_CLIENT_ID = None
SASHIMMIE_CLIENT_SECRET = None
SASHIMMIE_REFRESH_TOKEN = None
SASHIMMIE_TUMBLR_CONSUMER_KEY = None
SASHIMMIE_USER_AGENT = "sashimmie:v0.0.7 (by /u/ThePadawan)"
SASHIMMIE_REDDIT_USERNAME = None

SECRET_KEY = "CHANGE-ME_LATER"
