name: Keep pulled commits up-to-date
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # daily at 2am

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        run: pip install requests
      - name: Check remote heads for commit IDs
        run: python update.py
      - name: Debug output (should be skipped if 0 changes)
        if: ${{ $GITPOD_BEEVENUE_SUB_COUNT != "0" }}
        run: echo $GITPOD_BEEVENUE_SUB_COUNT
      - name: Commit files
        if: ${{ $GITPOD_BEEVENUE_SUB_COUNT != "0" }}
        run: |
          git config --local user.email "prbot@prat.ch"
          git config --local user.name "PRBot"
          git add .gitpod.Dockerfile
          git commit -m "Update remote head commit (x${GITPOD_BEEVENUE_SUB_COUNT})"
      - name: Push changes
        if: ${{ $GITPOD_BEEVENUE_SUB_COUNT != "0" }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
